(function(root){
const safeCell=v=>typeof v==='string'&&/^[\s]*[=+@-]/.test(v)?"'"+v:v;
function structured(){return ReportSnapshot.snapshot()}
const mdEscape=v=>String(v??'').replace(/([\\`*_{}\[\]<>#])/g,'\\$1').replace(/\|/g,'\\|').replace(/\r?\n/g,'<br>');
function readable(s,markdown){const lines=[];for(const b of structured().blocks){if(b.type==='image')continue;if(b.type==='heading')lines.push((markdown?'#'.repeat(b.level)+' ':'')+b.text);else if(b.type==='text')lines.push(b.text);else if(b.type==='list')lines.push(...b.items.map((v,i)=>(b.ordered?(i+1)+'. ':'- ')+v));else if(b.type==='table'){if(markdown){const rows=b.rows.map(r=>'| '+r.map(mdEscape).join(' | ')+' |');if(b.headerRows)rows.splice(b.headerRows,0,'| '+b.rows[0].map(()=>'---').join(' | ')+' |');lines.push(...rows)}else lines.push(...b.rows.map(r=>r.join(' | ')))}lines.push('')}return lines.join('\n')}
function flatRows(){const rows=[];structured().blocks.forEach((b,i)=>{if(b.type==='image')return;if(b.type==='table')b.rows.forEach((r,j)=>rows.push([i+1,j<b.headerRows?'Cabeçalho':'Linha da tabela',...r]));else if(b.type==='list')b.items.forEach((v,j)=>rows.push([i+1,'Item',b.ordered?(j+1)+'. '+v:v]));else rows.push([i+1,b.type==='heading'?'Título':'Texto',b.text])});return rows}
function delimited(s,sep){const rows=flatRows(),n=Math.max(3,...rows.map(r=>r.length)),quote=v=>'"'+String(safeCell(v)??'').replace(/"/g,'""')+'"';return '\uFEFF'+[['Ordem','Tipo',...Array.from({length:n-2},(_,i)=>'Conteúdo '+(i+1))],...rows.map(r=>[...r,...Array(n-r.length).fill('')])].map(r=>r.map(quote).join(sep)).join('\r\n')}
function jsonLines(){return structured().blocks.map((b,i)=>JSON.stringify({order:i+1,...b})).join('\n')+'\n'}
function workbook(){const book=XLSX.utils.book_new(),rows=[],tables=[];structured().blocks.forEach(b=>{if(b.type==='image')return;if(b.type==='table'){rows.push(...b.rows,[]);tables.push(b)}else if(b.type==='list')rows.push(...b.items.map((v,i)=>[b.ordered?(i+1)+'. '+v:v]),[]);else rows.push([b.text],[])});const sheet=XLSX.utils.aoa_to_sheet(rows);sheet['!cols']=Array.from({length:Math.max(1,...rows.map(r=>r.length))},()=>({wch:32}));sheet['!rows']=rows.map(r=>({hpt:r.length===1?Math.max(24,Math.ceil(String(r[0]||'').length/100)*16):32}));sheet['!merges']=rows.flatMap((r,i)=>r.length===1&&sheet['!cols'].length>1?[{s:{r:i,c:0},e:{r:i,c:sheet['!cols'].length-1}}]:[]);XLSX.utils.book_append_sheet(book,sheet,'Relatório');tables.forEach((b,i)=>{const sh=XLSX.utils.aoa_to_sheet(b.rows);sh['!cols']=b.rows[0].map(()=>({wch:28}));XLSX.utils.book_append_sheet(book,sh,'Tabela '+(i+1))});return XLSX.write(book,{type:'array',bookType:'xlsx'})}
root.DownloadFormats={structured,readable,delimited,jsonLines,workbook};
if(typeof document==='undefined')return;
const dialog=document.getElementById('downloadDialog'),status=document.getElementById('downloadStatus');
document.getElementById('downloadCenter').onclick=()=>{status.textContent='Exportações usam somente o conteúdo visível, na ordem da prévia. O backup conserva o projeto completo.';dialog.showModal()};document.getElementById('closeDownloads').onclick=()=>dialog.close();
async function htmlDocument(){return ReportSnapshot.visualHTML(await ReportSnapshot.capture())}
let busy=false;
for(const button of dialog.querySelectorAll('[data-download]'))button.onclick=async()=>{if(busy)return;const type=button.dataset.download;if(type==='docxvisual'){dialog.close();return ReportSnapshot.saveVisual('docx',button)}if(['pdf','docx','backup','png','eml'].includes(type)){dialog.close();document.getElementById({pdf:'pdf',docx:'word',backup:'save',png:'copyEmail',eml:'copyEmail'}[type]).click();return}dialog.close();if(!validateExport())return;dialog.showModal();busy=true;button.disabled=true;status.textContent='Preparando '+type.toUpperCase()+'…';try{const s=TrainingNarrative.prepare(state);let bytes,mime,extension=type;if(type==='html'){bytes=await htmlDocument();mime='text/html;charset=utf-8'}else if(type==='xlsx'){bytes=await root.StudioWorkbook();mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}else if(type==='csv'||type==='tsv'){bytes=delimited(s,type==='csv'?';':'\t');mime=type==='csv'?'text/csv;charset=utf-8':'text/tab-separated-values;charset=utf-8'}else if(type==='md'||type==='txt'){bytes=readable(s,type==='md');mime='text/plain;charset=utf-8'}else if(type==='json'){bytes=JSON.stringify(structured(s),null,2);mime='application/json'}else if(type==='jsonl'){bytes=jsonLines(s);mime='application/x-ndjson'}else throw Error('Formato não disponível.');download(bytes,slug()+(type==='json'?'-dados-ia':'')+'.'+extension,mime);status.textContent='Download de '+type.toUpperCase()+' preparado.'}catch(e){status.textContent='Não foi possível gerar: '+e.message}finally{busy=false;button.disabled=false}};
})(globalThis);
