(function(root){
const traits={engagement:['Participou ativamente','participação ativa nas atividades'],questions:['Fez perguntas relevantes','perguntas pertinentes aos temas trabalhados'],collaboration:['Colaborou com a turma','colaboração e troca de conhecimentos com a turma'],practice:['Aplicou os conceitos na prática','aplicação dos conceitos nas atividades práticas'],communication:['Demonstrou comunicação clara','clareza ao comunicar ideias e orientar respostas'],empathy:['Demonstrou escuta e empatia','escuta atenta e postura empática nas interações'],initiative:['Demonstrou iniciativa','iniciativa para participar e buscar soluções'],improvement:['Demonstrou evolução','evolução ao longo das atividades propostas'],tools:['Usou bem os sistemas','boa utilização das ferramentas e sistemas trabalhados'],commitment:['Demonstrou comprometimento','comprometimento com as atividades do treinamento']};
const join=a=>a.length<2?(a[0]||''):a.slice(0,-1).join(', ')+' e '+a.at(-1);
function seed(s,extra=''){let n=0;for(const c of [s.writingSeed||'',s.title||'',s.period||'',extra].join('|'))n=(n*31+c.charCodeAt(0))>>>0;return n+(Number(s.narrativeVariant)||0)}
function pick(s,key,items){return items[seed(s,key)%items.length]}
function dateText(v){return v?String(v).split('-').reverse().join('/'):''}
function period(s){if(s.startDate&&s.endDate)return s.startDate===s.endDate?dateText(s.startDate):dateText(s.startDate)+' a '+dateText(s.endDate);if(s.startDate)return'A partir de '+dateText(s.startDate);if(s.endDate)return'Até '+dateText(s.endDate);return s.period||''}
function filtered(s){return s.people.filter(p=>(s.reportMode!=='annual'||(p.trainingStart||p.trainingEnd||'').slice(0,4)===String(s.reportYear))&&(!s.reportSupervisor||(p.manager||'')===s.reportSupervisor)&&(!s.reportSector||(p.sector||'')===s.reportSector)&&(!s.reportTraining||(p.training||'')===s.reportTraining)&&(!s.filterPeriod||((p.trainingStart||'')+'|'+(p.trainingEnd||''))===s.filterPeriod)&&(!(s.filterStart||s.filterEnd)||((p.trainingStart||p.trainingEnd)&&(!s.filterStart||(p.trainingEnd||p.trainingStart)>=s.filterStart)&&(!s.filterEnd||(p.trainingStart||p.trainingEnd)<=s.filterEnd))))}

function groups(s){const groups=new Map();for(const p of s.people.filter(p=>p.name.trim())){const supervisor=p.manager?.trim()||'Supervisor não informado',sector=p.sector?.trim()||'Setor não informado',key=JSON.stringify([sector,supervisor]);if(!groups.has(key))groups.set(key,{sector,supervisor,people:[]});groups.get(key).people.push(p)}return[...groups.values()].sort((a,b)=>(a.sector+a.supervisor).localeCompare(b.sector+b.supervisor,'pt-BR')).map(g=>({...g,metrics:root.Report.metrics({...s,people:g.people})}))}
function recognitions(s){return s.people.filter(p=>(s.reportMode!=='annual'||(p.trainingStart||p.trainingEnd||'').slice(0,4)===String(s.reportYear))&&p.name.trim()&&p.recognize&&p.praise?.some(k=>traits[k])&&['Concluído','Em andamento'].includes(p.status)).map((p,index)=>{const observed=Object.keys(traits).filter(k=>p.praise.includes(k)).map(k=>traits[k][1]);const opening=[`${p.name} se destacou pela ${join(observed)}.`, `Durante ${s.title||'o treinamento'}, ${p.name} demonstrou ${join(observed)}.`, `Reconheço ${p.name} pela ${join(observed)}.`, `Destaco a participação de ${p.name} pela ${join(observed)}.`][(seed(s,p.name)+index)%4];let detail=p.recognitionNote?.trim();const identity=[s.reportMode==='annual'&&p.training?'Treinamento: '+p.training:'',p.sector?'Setor: '+p.sector:'',p.manager?'Supervisor: '+p.manager:''].filter(Boolean).join(' · ');return{name:p.name,identity,text:opening+(detail?' '+detail:''),person:p}})}
function prepare(s){const out={...s,period:period(s),people:filtered(s).slice().sort((a,b)=>((a.sector||'')+'|'+(a.manager||'')+'|'+a.name).localeCompare((b.sector||'')+'|'+(b.manager||'')+'|'+b.name,'pt-BR'))};if(s.reportTraining)out.title=s.reportTraining;if(s.filterStart||s.filterEnd)out.period=period({startDate:s.filterStart,endDate:s.filterEnd});else if(s.filterPeriod){const [startDate,endDate]=s.filterPeriod.split('|');out.period=period({startDate,endDate})||'Sem data'}if(s.reportMode==='annual'){out.period='01/01/'+s.reportYear+' a 31/12/'+s.reportYear;out.title=(s.title||'Balanço anual de treinamentos')+' · '+s.reportYear;out.hours='';out.classes='';out.invited='';out.platform='';out.link='';out.annual=annual(out)}if(!out.reportLogo&&root.BrandMedia)out.reportLogo=root.BrandMedia.logoData;out.scopeLabel=[s.reportMode==='annual'?'Consolidado anual · '+s.reportYear:'',s.reportTraining?'Treinamento: '+s.reportTraining:'',(s.filterStart||s.filterEnd||s.filterPeriod)?'Período selecionado: '+out.period:'',s.reportSupervisor?'Supervisor: '+s.reportSupervisor:'',s.reportSector?'Setor: '+s.reportSector:''].filter(Boolean).join(' · ');if(out.scopeLabel)out.invited='';if(root.ContentBuilder&&s.contentBuilder){const auto=root.ContentBuilder.compose(out);for(const k of root.ContentBuilder.fields)if(s.contentBuilder.auto[k])out[k]=auto[k]}return out}

function annual(s){
 const rows=s.people.filter(p=>p.name.trim()),normalize=v=>String(v||'').trim().toLocaleLowerCase('pt-BR'),personKey=p=>normalize(p.email)||normalize(p.name),eventKey=p=>JSON.stringify([normalize(p.training),p.trainingStart||'',p.trainingEnd||'']);
 const aggregate=people=>{const m=root.Report.metrics({...s,people});return {...m,unique:new Set(people.map(personKey)).size,events:new Set(people.filter(p=>p.training.trim()).map(eventKey)).size}};
 const total=aggregate(rows),labels=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];
 const months=labels.map((label,i)=>({label,...aggregate(rows.filter(p=>Number((p.trainingStart||p.trainingEnd).slice(5,7))===i+1))}));
 const names=[...new Set(rows.map(p=>p.training.trim()||'Treinamento não informado'))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
 const trainings=names.map(label=>({label,...aggregate(rows.filter(p=>(p.training.trim()||'Treinamento não informado')===label))}));
 const active=months.filter(m=>m.registered),peak=Math.max(0,...months.map(m=>m.registered)),leaders=months.filter(m=>m.registered===peak&&peak).map(m=>m.label);
 const text=rows.length?`Em ${s.reportYear}, o recorte reúne ${total.registered} inscrições em treinamentos, envolvendo ${total.unique} pessoas identificadas por e-mail ou, quando ausente, por nome. Foram identificadas ${total.events} combinações de treinamento e período, distribuídas em ${active.length} meses com registros.\n\nDas inscrições, ${total.participants} têm participação registrada (concluídas ou em andamento), ${total.approved} atendem aos critérios de aprovação, ${total.failed} não atendem, ${total.pending} aguardam conclusão ou avaliação e ${total.absent} constam como ausentes. A média das ${total.graded} inscrições concluídas com nota é ${root.Report.fmt(total.average)}.\n\nMaior volume de inscrições: ${leaders.join(', ')} (${peak} em cada mês indicado).`:`Nenhum registro com data foi encontrado para ${s.reportYear} no recorte selecionado. Importe a planilha ou revise as datas e os filtros.`;
 const methodology='Cada linha corresponde a uma inscrição, portanto uma pessoa pode aparecer em vários treinamentos. Pessoas únicas: e-mail, com nome como alternativa; nomes iguais sem e-mail podem ser agrupados. Edições: combinações de nome do treinamento, início e término, sem diferenciar turmas no mesmo período. O mês e o ano usam o início, ou o término quando não há início. Meses zerados indicam ausência de registros na base, não comprovam ausência de atividade. Registros sem data são excluídos. Aprovação usa os critérios definidos neste painel para todo o recorte.';
 const headers=['Período','Inscrições','Participações','Aprovadas','Média'];
 const tableRow=m=>[m.label,String(m.registered),String(m.participants),String(m.approved),root.Report.fmt(m.average)];
 return {total,months,trainings,text,methodology,sections:[{id:'annualOverview',title:'Panorama executivo do ano',text,annualCards:[['Pessoas únicas',total.unique],['Inscrições',total.registered],['Edições identificadas',total.events],['Meses com registros',active.length]]},{id:'annualMonths',title:'Evolução mensal',text:'Distribuição das inscrições e dos resultados ao longo do ano.',headers,rows:months.map(tableRow),months},{id:'annualTrainings',title:'Portfólio de treinamentos',text:'Resultados por treinamento no recorte selecionado.',headers:['Treinamento',...headers.slice(1)],rows:trainings.map(tableRow)},{id:'annualMethod',title:'Como ler estes resultados',text:methodology}]};
}
const count=(n,one,many=one+'s')=>n+' '+(n===1?one:many);
root.TrainingNarrative={count,traits,join,seed,pick,period,filtered,groups,recognitions,prepare,annual};
})(typeof window!=='undefined'?window:globalThis);
