function atlasReport(html,s,m){
 const box=document.createElement('div');box.innerHTML=html;
 const oldChart=box.querySelector('.distribution-bar');
 if(oldChart&&m.registered){
  const values=[['Aprovados',m.approved,s.theme==='b2b'?'#253072':'#d61960'],['Reprovados',m.failed,s.theme==='b2b'?'#091441':'#bd1d3f'],['Pendentes',m.pending,'#f4922d'],['Ausentes',m.absent,'#9a9b9e']];
  const max=Math.max(1,...values.map(v=>v[1]));
  const chart=document.createElement('div');chart.className='results-chart';chart.setAttribute('role','img');chart.setAttribute('aria-label','Gráfico do panorama da turma');
  chart.innerHTML='<div class="chart-scale"><span>'+max+'</span><span>'+Math.round(max/2)+'</span><span>0</span></div><div class="chart-plot">'+values.map(([label,value,color])=>'<div class="chart-column"><strong>'+value+'</strong><i style="height:'+Math.max(value?8:0,value/max*100)+'%;background:'+color+'"></i><span>'+label+'</span></div>').join('')+'</div>';
  oldChart.replaceWith(chart);
 }
 box.querySelector('.preview-cover')?.remove();box.querySelector('.report-logo')?.remove();box.querySelector('.subtitle')?.remove();box.querySelector('.meta')?.remove();
 const e=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const annual=s.reportMode==='annual',brand=s.theme==='b2b'?'B2B':'VERO';
 const overview=annual?s.annual?.total:null;
 const stats=annual?[['Pessoas',overview?.unique??0],['Inscrições',overview?.registered??0],['Edições',overview?.events??0],['Carga horária'+(overview?.workload?.missing||overview?.workload?.conflicts?' (parcial)':''),overview?.workload?.known?Report.fmt(overview.workload.hours)+' h':'Não informada']]:[['Participantes',m.participants],['Média da prova',Report.fmt(m.average)],['Aprovados',m.approved],['Carga horária',Report.numeric(s.hours)?Report.fmt(s.hours)+' h':'Não informada']];
 const duration=stats.at(-1)[1];
 let cover=`<div class="signature-cover"><div class="signature-head"><div class="signature-logo ${s.reportLogo===window.BrandMedia?.logoFor(s)?'signature-logo-default':''}">${s.reportLogo?`<img src="${e(s.reportLogo)}" alt="Logotipo">`:'<strong>T&D</strong>'}</div><div class="signature-identity"><strong>${brand}</strong><span>TREINAMENTO &<br>DESENVOLVIMENTO</span></div></div><div class="signature-intro"><div class="signature-eyebrow"><span>${annual?'BALANÇO ANUAL':'RELATÓRIO DE TREINAMENTO'}</span><i aria-hidden="true"></i><span>${annual?e(s.reportYear):'APRENDIZAGEM'}</span></div><h1 class="signature-title">${e(s.title||'Seu próximo treinamento')}</h1>${s.reportSubtitle?`<p class="signature-subtitle">${e(s.reportSubtitle)}</p>`:''}</div><div class="signature-stage"><div class="signature-facts"><p class="signature-company">${e(s.company||'Treinamento & desenvolvimento')}</p><div class="signature-fact"><span class="signature-index" aria-hidden="true">01</span><div><small>PERÍODO</small><strong>${e(s.period||'A informar')}</strong></div></div><div class="signature-fact"><span class="signature-index" aria-hidden="true">02</span><div><small>RESPONSÁVEL</small><strong>${e(s.facilitator||'A informar')}</strong></div></div><div class="signature-fact"><span class="signature-index" aria-hidden="true">03</span><div><small>${annual?'CARGA HORÁRIA DO ANO':'CARGA HORÁRIA'}</small><strong>${e(duration)}</strong></div></div></div><div class="signature-visual"><div class="signature-orbit" aria-hidden="true"></div><div class="signature-disc signature-disc-orange" aria-hidden="true"></div><div class="signature-disc signature-disc-brand" aria-hidden="true"></div><img class="signature-person" src="${e(s.reportPortrait||BrandMedia.portraitURL)}" alt="Personagem do relatório"></div></div><div class="signature-caption"><span>${e(s.scopeLabel||'Visão consolidada da turma')}</span><b>${annual?'BALANÇO / '+e(s.reportYear):'DESENVOLVIMENTO DE PESSOAS'}</b></div></div><div class="cover-scorecard">${stats.map(([label,value])=>`<div><strong>${e(value)}</strong><span>${label}</span></div>`).join('')}</div>`;
 if(s.reportStyle==='magazine'){
 const shell=document.createElement('div');shell.innerHTML=cover;const mast=shell.querySelector('.signature-head').outerHTML;
 cover=`<div class="art-cover">${mast}<div class="art-kicker"><span>PESSOAS / CONHECIMENTO / RESULTADOS</span><b>${annual?e(s.reportYear):'T&D'}</b></div><div class="art-masthead">EM FOCO<span aria-hidden="true">.</span></div><div class="art-spread"><div class="art-story"><p class="art-edition">${annual?'EDIÇÃO ANUAL':'EDIÇÃO TREINAMENTO'}</p><h1>${e(s.title||'Seu próximo treinamento')}</h1>${s.reportSubtitle?`<p class="art-deck">${e(s.reportSubtitle)}</p>`:''}<div class="art-details"><p><small>QUANDO</small><b>${e(s.period||'A informar')}</b></p><p><small>QUEM CONDUZ</small><b>${e(s.facilitator||'A informar')}</b></p><p><small>CARGA HORÁRIA</small><b>${e(duration)}</b></p></div></div><div class="art-photo"><div class="art-photo-ring" aria-hidden="true"></div><span class="art-photo-type" aria-hidden="true">T&D</span><img src="${e(s.reportPortrait||BrandMedia.portraitURL)}" alt="Personagem do relatório"><span class="art-photo-caption">APRENDER. APLICAR. EVOLUIR.</span></div></div><div class="art-cover-footer"><span>${e(s.company||'Treinamento & desenvolvimento')}</span><b>${e(s.scopeLabel||'Visão consolidada da turma')}</b></div></div><div class="art-stats">${stats.map(([label,value],i)=>`<div><small>${String(i+1).padStart(2,'0')} / ${label}</small><strong>${e(value)}</strong></div>`).join('')}</div>`;
 }
 box.querySelectorAll('.analysis-block').forEach((card,i)=>{const heading=card.querySelector('b')?.textContent||'';card.classList.add(/CONTEXTO/.test(heading)?'analysis-context':/DESENVOLVIMENTO/.test(heading)?'analysis-development':/PASSOS|AÇÃO|ACO|ACOMPANHAMENTO/.test(heading)?'analysis-action':'analysis-results');});
 // Group each section so its heading, content and visual rhythm stay together.
 const body=document.createElement('div');body.className='atlas-body';let section=body;
 for(const child of [...box.childNodes]){if(child.nodeType===1&&child.tagName==='H3'){section=document.createElement('section');section.className='report-section';body.append(section)}section.append(child)}
 return cover+body.outerHTML;
}
