(function(root){
const themes={b2b:{accent:'#253072',secondary:'#f4922d',deep:'#091441',bright:'#25489e',swatches:['#253072','#091441','#25489e','#f4922d','#ffffff'],weights:[3,1,1,1,1]},rose:{accent:'#d61960',secondary:'#f4922d',deep:'#830f2e',bright:'#d61960',swatches:['#d61960','#f4922d','#fdd206','#bd1d3f','#830f2e','#f0628c','#f384a5','#ffffff'],weights:[6.6,6.6,1,3,1,.9,3,3]}};
const columnNames={trainingHours:'Carga horária',training:'Treinamento',trainingStart:'Início',trainingEnd:'Término',name:'Colaborador',manager:'Supervisor',sector:'Setor',grade:'Nota',attendance:'Presença',status:'Situação',result:'Resultado',email:'E-mail',phone:'Telefone',notes:'Observações'};
const sectionNames={summary:'Resumo do treinamento',people:'Participantes e resultados',objective:'Objetivo',topics:'Temas abordados',schedule:'Cronograma',teams:'Resultados por supervisor e setor',recognition:'Reconhecimentos individuais',analysis:'Análise e próximos passos'};
const numeric=v=>v!==''&&v!==null&&v!==undefined&&Number.isFinite(Number(v));
function result(p,s){if(p.status==='Ausente')return 'Ausente';if(p.status==='Pendente')return 'Pendente';if(p.status==='Em andamento')return 'Em andamento';if(!numeric(p.grade)||!numeric(p.attendance))return 'A avaliar';return Number(p.grade)>=Number(s.minGrade)&&Number(p.attendance)>=Number(s.minAttendance)?'Aprovado':'Reprovado'}
function metrics(s){const people=s.people.filter(p=>p.name.trim());const present=people.filter(p=>['Concluído','Em andamento'].includes(p.status));const graded=people.filter(p=>p.status==='Concluído'&&numeric(p.grade));return{registered:people.length,participants:present.length,average:graded.length?graded.reduce((v,p)=>v+Number(p.grade),0)/graded.length:null,graded:graded.length,approved:people.filter(p=>result(p,s)==='Aprovado').length,failed:people.filter(p=>result(p,s)==='Reprovado').length,pending:people.filter(p=>['A avaliar','Pendente','Em andamento'].includes(result(p,s))).length,absent:people.filter(p=>p.status==='Ausente').length}}
const fmt=n=>n===null||n===undefined||n===''?'—':Number(n).toLocaleString('pt-BR',{maximumFractionDigits:2});
function value(p,col,s){if(col==='trainingHours')return numeric(p.trainingHours)?fmt(p.trainingHours)+' h':'—';if(['trainingStart','trainingEnd'].includes(col))return p[col]?p[col].split('-').reverse().join('/'):'—';if(col==='result')return result(p,s);if(col==='grade')return numeric(p.grade)?fmt(p.grade):'—';if(col==='attendance')return numeric(p.attendance)?fmt(p.attendance)+'%':'—';return p[col]||'—'}
function sections(s){if(s.reportMode==='annual'&&s.annual){const enabled=id=>s.sections.some(x=>x.id===id&&x.enabled);const detail=sections({...s,reportMode:'training',sections:s.sections.filter(x=>['teams','recognition','people'].includes(x.id)||s.custom.some(c=>c.id===x.id))});return [...(enabled('summary')?s.annual.sections.slice(0,3):[]),...detail,...(s.annualNotes?[{id:'annualNotes',title:'Balanço do ano e prioridades',text:s.annualNotes}]:[]),s.annual.sections[3]]}return s.sections.filter(x=>x.enabled&&(x.id!=='recognition'||root.TrainingNarrative.recognitions(s).length)&&(x.id!=='teams'||s.people.some(p=>p.name.trim()))).map(x=>({...x,title:sectionNames[x.id]||s.custom.find(c=>c.id===x.id)?.title||'Seção adicional',text:(x.id==='recognition'?root.TrainingNarrative.recognitions(s).map(r=>r.name+'\n'+r.identity+'\n'+r.text).join('\n\n'):s[x.id])||s.custom.find(c=>c.id===x.id)?.body||''}))}
async function makePDF(s){
const {PDFDocument,rgb,PDFName,PDFString}=root.PDFLib,doc=await PDFDocument.create();
doc.registerFontkit(root.fontkit);const fontData=root.ReportFontData||await Promise.all(['Arimo-Regular.ttf','Arimo-Bold.ttf'].map(async name=>{const r=await fetch('fonts/'+name);if(!r.ok)throw Error('Não foi possível carregar a tipografia do relatório.');return new Uint8Array(await r.arrayBuffer())}));
const normal=await doc.embedFont(fontData[0],{subset:true}),bold=await doc.embedFont(fontData[1],{subset:true});
doc.setTitle(s.title||'Relatório de treinamento');doc.setAuthor(s.author||s.facilitator||'');doc.setSubject('Desenvolvimento, participação e aprendizagem');
const palette=s.theme==='b2b'?themes.b2b:['premium','executive','magazine'].includes(s.reportStyle)?themes.rose:themes[s.theme]||themes.rose,C=h=>rgb(parseInt(h.slice(1,3),16)/255,parseInt(h.slice(3,5),16)/255,parseInt(h.slice(5,7),16)/255);
const accent=C(palette.accent),second=C(palette.secondary),ink=C('#5f5f5f'),muted=C('#5f5f5f'),pale=C('#edf0ee'),white=C('#ffffff'),line=C('#d3d2cf'),green=C(s.theme==='b2b'?'#25489e':'#f4922d'),red=C(s.theme==='b2b'?'#091441':'#bd1d3f'),amber=C(s.theme==='b2b'?'#f4922d':'#f384a5');
const W=595.28,H=841.89,M=42,CW=W-M*2,BOTTOM=H-57,compact=s.reportStyle==='compact';let page,y=0,activeSection='',logo=null;const pagesMeta=[];
if(!s.reportLogo&&root.BrandMedia)s={...s,reportLogo:root.BrandMedia.logoFor(s)};let portrait=null;if(['premium','executive','magazine'].includes(s.reportStyle)&&root.BrandMedia){const media=await root.BrandMedia.getPortrait(s);portrait=media.type==='png'?await doc.embedPng(media.data):await doc.embedJpg(media.data);}
if(s.reportLogo){try{logo=s.reportLogo.startsWith('data:image/png')?await doc.embedPng(s.reportLogo):await doc.embedJpg(s.reportLogo)}catch{throw Error('O logotipo não pôde ser usado no PDF. Remova-o ou escolha outro PNG/JPG.')}}
const validChars=new Set(normal.getCharacterSet());const clean=t=>Array.from(String(t??'').normalize('NFC').replace(/\t/g,'    ').replace(/\r/g,'')).filter(c=>c==='\n'||validChars.has(c.codePointAt(0))).join('');
function rect(x,top,w,h,color,opacity=1){page.drawRectangle({x,y:H-top-h,width:w,height:h,color,opacity})}
function circle(x,top,size,color,opacity=1){page.drawCircle({x,y:H-top,size,color,opacity})}
function txt(t,x,top,size=10,font=normal,color=ink){page.drawText(clean(t),{x,y:H-top-size,size,font,color})}
function rule(x,top,w,color=line){rect(x,top,w,.7,color)}
function wrap(t,width,size=10,font=normal){const out=[];for(const para of clean(t).split('\n')){let l='';for(const word of para.split(/\s+/)){if(!word)continue;let chunks=[],p='';for(const ch of word){if(font.widthOfTextAtSize(p+ch,size)>width&&p){chunks.push(p);p=ch}else p+=ch}if(p)chunks.push(p);for(const c of chunks){if(l&&font.widthOfTextAtSize(l+' '+c,size)>width){out.push(l);l=c}else l=l?l+' '+c:c}}out.push(l)}return out}
function fit(t,width,size=8,font=normal){let st=clean(t).replace(/\n/g,' ');while(font.widthOfTextAtSize(st,size)>width&&st.length)st=st.slice(0,-1);return st}
function drawLogo(x,top,maxW,maxH){if(!logo)return;const defaultB2B=s.theme==='b2b'&&s.reportLogo===root.BrandMedia?.b2bLogoData;const ratio=defaultB2B?maxW*1.12/logo.width:Math.min(maxW/logo.width,maxH/logo.height);page.drawImage(logo,{x,y:H-top-logo.height*ratio,width:logo.width*ratio,height:logo.height*ratio})}
function newPage(cover=false){page=doc.addPage([W,H]);pagesMeta.push({cover});y=80;rect(0,0,W,5,accent);if(!cover){txt(fit(s.company||'TREINAMENTO & DESENVOLVIMENTO',CW-100,8,bold),M,26,8,bold,accent);txt(fit(activeSection||s.title||'Relatório de treinamento',CW-100,7),M,42,7,normal,muted);if(logo)drawLogo(W-M-70,21,70,31);rule(M,63,CW)}}
function ensure(h){if(y+h>BOTTOM)newPage()}
function paragraph(t,size=9.5,color=ink,font=normal,x=M,width=CW){const lines=wrap(t,width,size,font),lh=size*1.6;for(const l of lines){ensure(lh);if(l)txt(l,x,y,size,font,color);y+=lh}y+=7}
function heading(t,index){activeSection=t;if(s.reportStyle==='magazine'){const lines=wrap(t,CW-65,20,bold);ensure(lines.length*26+66);rule(M,y,CW,accent);txt(String(index).padStart(2,'0'),M,y+10,34,normal,accent);lines.forEach((l,i)=>txt(l,M+65,y+16+i*26,20,bold,accent));y+=Math.max(65,lines.length*26+36);return}const required=wrap(t,CW-38,17,bold).length*23+55;ensure(required);rect(M,y+2,25,25,accent);txt(String(index).padStart(2,'0'),M+5,y+7,10,bold,white);const lines=wrap(t,CW-38,17,bold);lines.forEach((l,i)=>txt(l,M+38,y+i*23,17,bold));y+=Math.max(38,lines.length*23+13)}
function callout(title,body,tint=accent){const lines=wrap(body,CW-36,9.5),lh=15;const blockHeight=34+wrap(title,CW-36,8,bold).length*12+lines.length*lh;if(blockHeight<=BOTTOM-80)ensure(blockHeight);let offset=0;do{ensure(70+wrap(title,CW-36,8,bold).length*12);const n=Math.max(1,Math.min(lines.length-offset,Math.floor((BOTTOM-y-45-wrap(title,CW-36,8,bold).length*12)/lh)));const titleLines=wrap(title+(offset?' · continuação':''),CW-36,8,bold);const part=lines.slice(offset,offset+n),h=24+titleLines.length*12+part.length*lh;rect(M,y,CW,h,pale);rect(M,y,4,h,tint);titleLines.forEach((l,i)=>txt(l,M+18,y+12+i*12,8,bold,accent));part.forEach((l,i)=>txt(l,M+18,y+21+titleLines.length*12+i*lh,9.5));y+=h+10;offset+=n}while(offset<lines.length)}
function infoPairs(pairs){for(let i=0;i<pairs.length;i+=2){const row=pairs.slice(i,i+2),width=(CW-22)/2;const cells=row.map(([label,v])=>({label,lines:wrap(v,width,9)}));const h=20+Math.max(...cells.map(c=>c.lines.length))*14;ensure(h+12);cells.forEach((c,j)=>{const x=M+j*(width+22);txt(c.label.toLocaleUpperCase('pt-BR'),x,y,6.5,bold,muted);c.lines.forEach((l,k)=>txt(l,x,y+15+k*14,9))});y+=h+13}y+=5}
function metricCards(m){const cards=[['PARTICIPANTES',m.participants,'Pessoas que iniciaram ou concluíram'],['MÉDIA DA PROVA',fmt(m.average),m.graded+' concluintes com nota informada'],['APROVADOS',m.approved,'Nota e presença atendem aos critérios']];const w=(CW-18)/3;ensure(91);cards.forEach(([label,v,sub],i)=>{const x=M+i*(w+9);rect(x,y,w,80,i===0?accent:pale);txt(label,x+12,y+11,6.6,bold,i===0?white:muted);txt(String(v),x+12,y+24,27,bold,i===0?white:accent);wrap(sub,w-24,6.2).forEach((l,k)=>txt(l,x+12,y+60+k*9,6.2,normal,i===0?white:muted))});y+=97}
function distribution(m){if(!m.registered)return;ensure(205);txt('PANORAMA DA TURMA',M,y,8,bold,ink);txt('Base: '+m.registered+' pessoas cadastradas',M,y+15,7,normal,muted);y+=38;const vals=[['APROVADOS',m.approved,green],['REPROVADOS',m.failed,red],['PENDENTES',m.pending,amber],['AUSENTES',m.absent,C('#9a9b9e')]],chartH=105,gap=18,barW=(CW-gap*5)/4,max=Math.max(1,...vals.map(v=>v[1]));rule(M,y+chartH,CW,C('#d3d2cf'));for(let g=0;g<=2;g++)rule(M,y+g*chartH/2,CW,C('#edf0ee'));vals.forEach(([label,n,color],i)=>{const x=M+gap+i*(barW+gap),h=chartH*n/max;rect(x,y+chartH-h,barW,h,color);const value=String(n);txt(value,x+(barW-bold.widthOfTextAtSize(value,9))/2,y+chartH-h-15,9,bold,accent);txt(fit(label,barW,6,bold),x,y+chartH+10,6,bold,muted)});y+=chartH+39}
function topicCards(items){if(!items.length){paragraph('Não informado.',9,muted);return}if(compact){items.forEach((v,i)=>paragraph(String(i+1).padStart(2,'0')+'  '+v));return}const gap=12,w=(CW-gap)/2;for(let i=0;i<items.length;i+=2){const row=items.slice(i,i+2),lines=row.map(t=>wrap(t,w-42,9));const height=Math.max(63,Math.max(...lines.map(a=>a.length))*14+24);if(height>BOTTOM-90){row.forEach((t,j)=>callout('TEMA '+String(i+j+1).padStart(2,'0'),t));continue}ensure(height+12);row.forEach((t,j)=>{const x=M+j*(w+gap);rect(x,y,w,height,pale);txt(String(i+j+1).padStart(2,'0'),x+11,y+13,9,bold,accent);lines[j].forEach((l,k)=>txt(l,x+34,y+13+k*14,9))});y+=height+12}}
function timeline(items){if(!items.length){paragraph('Não informado.',9,muted);return}items.forEach((item,i)=>{const lines=wrap(item,CW-52,10),h=lines.length*16+26;if(h>BOTTOM-90){callout('ETAPA '+(i+1),item,second);return}ensure(h);rect(M+12,y+10,1,h,line);page.drawCircle({x:M+12,y:H-y-12,size:11,color:accent});const label=String(i+1);txt(label,M+12-bold.widthOfTextAtSize(label,8)/2,y+6,8,bold,white);lines.forEach((l,k)=>txt(l,M+39,y+3+k*16,10));y+=h});y+=3}
function table(cols,rows,raw=false){const weights=cols.map(k=>({name:1.8,manager:1.35,sector:1.1,grade:.7,attendance:1,status:1.2,result:1.2,email:1.7,phone:1.2,notes:1.7}[k]||1)),sum=weights.reduce((a,b)=>a+b,0),widths=weights.map(w=>CW*w/sum),size=cols.length>6?6.8:8;const lh=size*1.6;
function th(){ensure(61);const hs=cols.map((k,i)=>wrap(raw?k:columnNames[k],widths[i]-12,7,bold)),h=Math.max(...hs.map(a=>a.length))*10+16;rect(M,y,CW,h,ink);let x=M;hs.forEach((ls,i)=>{ls.forEach((l,j)=>txt(l,x+6,y+8+j*10,7,bold,white));x+=widths[i]});y+=h}
th();for(let ri=0;ri<rows.length;ri++){const p=rows[ri],lines=cols.map((k,i)=>wrap(raw?p[i]:value(p,k,s),widths[i]-12,size,k==='name'?bold:normal));let remaining=Math.max(...lines.map(a=>a.length)),offset=0;while(remaining>0){if(y+lh+17>BOTTOM){newPage();th()}let n=Math.min(remaining,Math.max(1,Math.floor((BOTTOM-y-17)/lh))),h=n*lh+17;if(ri%2===0)rect(M,y,CW,h,pale);let x=M;cols.forEach((k,i)=>{const v=raw?p[i]:value(p,k,s);const rc=k==='result'?(v==='Aprovado'?C('#5f5f5f'):v==='Reprovado'?red:C(s.theme==='b2b'?'#091441':'#830f2e')):ink;lines[i].slice(offset,offset+n).forEach((l,j)=>txt(l,x+6,y+8+j*lh,size,k==='name'||k==='result'?bold:normal,rc));x+=widths[i]});y+=h;rule(M,y,CW);offset+=n;remaining-=n;if(remaining){newPage();th()}}}y+=20}
newPage(true);
if(s.reportStyle==='magazine'){
rect(0,0,W,5,white);if(logo)drawLogo(M,30,105,43);
txt('PESSOAS / CONHECIMENTO / RESULTADOS',M,106,7,bold,accent);txt(s.reportMode==='annual'?s.reportYear:'T&D',W-M-32,106,8,bold,accent);rule(M,125,CW,accent);
txt('EM FOCO',M,131,65,bold,accent);circle(W-M-17,185,7,second);rect(M,213,CW,4,accent);
const leftW=245,rightX=M+leftW+24,rightW=CW-leftW-24;
txt(s.reportMode==='annual'?'EDIÇÃO ANUAL':'EDIÇÃO TREINAMENTO',M,240,8,bold,accent);
let size=29;while(size>16&&wrap(s.title||'Seu próximo treinamento',leftW,size,bold).length*size*1.16>170)size--;
let top=264;for(const l of wrap(s.title||'Seu próximo treinamento',leftW,size,bold)){txt(l,M,top,size,bold,accent);top+=size*1.16}
if(s.reportSubtitle){top+=14;for(const l of wrap(s.reportSubtitle,leftW-10,9).slice(0,3)){txt(l,M+8,top,9,normal,muted);top+=13}rect(M,top-39,2,39,second)}
rect(rightX,241,rightW,395,second);page.drawCircle({x:rightX+rightW/2,y:H-414,size:rightW*.46,borderColor:accent,borderWidth:.8});
if(portrait){const fit=root.BrandMedia.fitPortrait(portrait.width,portrait.height,rightW,340);page.drawImage(portrait,{x:rightX+(rightW-fit.width)/2,y:H-612,width:fit.width,height:fit.height})}
rect(rightX,612,rightW,24,accent);txt('APRENDER. APLICAR. EVOLUIR.',rightX+12,620,6.5,bold,white);
const a=s.annual?.total,load=s.reportMode==='annual'?(a?.workload?.known?fmt(a.workload.hours)+' h'+(a.workload.missing||a.workload.conflicts?' (parcial)':''):'Não informada'):numeric(s.hours)?fmt(s.hours)+' h':'Não informada';
let iy=Math.max(486,top+15);for(const [label,value]of [['QUANDO',s.period||'A informar'],['QUEM CONDUZ',s.facilitator||'A informar'],['CARGA HORÁRIA',load]]){txt(label,M,iy,6.5,normal,muted);wrap(value,leftW,9,bold).slice(0,2).forEach((l,j)=>txt(l,M,iy+13+j*12,9,bold,accent));iy+=47}
rule(M,654,CW,accent);txt(fit(s.company||'Treinamento & desenvolvimento',CW,8),M,665,8,normal,muted);
const m=metrics(s),stats=s.reportMode==='annual'?[['PESSOAS',a?.unique??0],['INSCRIÇÕES',a?.registered??0],['EDIÇÕES',a?.events??0],['CARGA HORÁRIA',load]]:[['PARTICIPANTES',m.participants],['MÉDIA DA PROVA',fmt(m.average)],['APROVADOS',m.approved],['CARGA HORÁRIA',load]];
stats.forEach(([label,value],i)=>{const x=M+i*CW/4,w=CW/4;if(i===0)rect(x,695,w,83,accent);else rule(x,695,w,accent);txt(String(i+1).padStart(2,'0')+' / '+label,x+10,706,6,bold,i===0?white:accent);txt(fit(String(value),w-20,22,bold),x+10,733,22,bold,i===0?white:accent)});newPage();
}else if(['premium','executive'].includes(s.reportStyle)){
const deep=C(palette.deep),bright=C(palette.bright),edge=C('#d3d2cf');
rect(0,0,W,5,white);if(s.reportStyle==='executive')rect(18,115,5,650,accent);if(s.reportStyle==='magazine')rect(M,112,CW,5,second);
if(logo)drawLogo(M,40,105,43);
const badge=s.theme==='b2b'?'B2B':'VERO';txt(badge,W-M-130,51,10,bold,accent);txt('TREINAMENTO &',W-M-83,46,6.5,normal,muted);txt('DESENVOLVIMENTO',W-M-83,57,6.5,normal,muted);rule(M,102,CW,edge);
txt(s.reportMode==='annual'?'BALANÇO ANUAL / '+s.reportYear:'RELATÓRIO DE TREINAMENTO / APRENDIZAGEM',M,130,8,bold,accent);
let titleSize=34;while(titleSize>20&&wrap(s.title||'Seu próximo treinamento',CW,titleSize,bold).length*titleSize*1.13>153)titleSize--;
let top=157;for(const l of wrap(s.title||'Seu próximo treinamento',CW,titleSize,bold)){txt(l,s.reportStyle==='magazine'?(W-bold.widthOfTextAtSize(l,titleSize))/2:M,top,titleSize,bold,accent);top+=titleSize*1.13}
if(s.reportSubtitle){top+=17;for(const l of wrap(s.reportSubtitle,CW-30,10).slice(0,4)){txt(l,M,top,10,normal,muted);top+=15}}
const stageTop=Math.max(338,top+20),stageBottom=650,stageH=stageBottom-stageTop;
const cx=W-M-102,cy=stageTop+stageH/2;
if(s.reportStyle==='executive'){rect(W-M-212,stageTop,212,stageH,pale);rect(W-M-212,stageTop,4,stageH,accent)}else if(s.reportStyle==='magazine'){rect(W-M-212,stageTop,212,stageH,second)}
if(s.reportStyle!=='executive'){
page.drawCircle({x:cx,y:H-cy,size:Math.min(118,stageH/2-5),borderColor:accent,borderWidth:.65});
circle(cx-35,cy-5,82,second);circle(cx+30,cy+24,76,s.theme==='b2b'?bright:accent);
}
if(portrait){const fit=root.BrandMedia.fitPortrait(portrait.width,portrait.height,210,stageH-4);page.drawImage(portrait,{x:W-M-fit.width,y:H-stageBottom,width:fit.width,height:fit.height})}
let infoTop=stageTop+8;for(const l of wrap(s.company||'Treinamento & desenvolvimento',245,8).slice(0,2)){txt(l,M,infoTop,8,normal,muted);infoTop+=12}infoTop+=15;
const a=s.annual?.total,load=s.reportMode==='annual'?(a?.workload?.known?fmt(a.workload.hours)+' h'+(a.workload.missing||a.workload.conflicts?' (parcial)':''):'Não informada'):numeric(s.hours)?fmt(s.hours)+' h':'Não informada';
for(const [i,[label,value]]of [['PERÍODO',s.period||'A informar'],['RESPONSÁVEL',s.facilitator||'A informar'],['CARGA HORÁRIA',load]].entries()){rule(M,infoTop,242,edge);txt(String(i+1).padStart(2,'0'),M,infoTop+13,8,normal,accent);txt(label,M+25,infoTop+11,7,normal,muted);const ls=wrap(value,211,10,bold).slice(0,3);ls.forEach((l,j)=>txt(l,M+25,infoTop+27+j*14,10,bold,deep));infoTop+=Math.max(65,43+ls.length*14)}
rect(M,stageBottom,CW,1.5,accent);wrap(s.scopeLabel||'Visão consolidada da turma',CW,8).slice(0,2).forEach((l,i)=>txt(l,M,665+i*12,8,normal,muted));
const m=metrics(s),stats=s.reportMode==='annual'?[['PESSOAS',a?.unique??0],['INSCRIÇÕES',a?.registered??0],['EDIÇÕES',a?.events??0]]:[['PARTICIPANTES',m.participants],['MÉDIA DA PROVA',fmt(m.average)],['APROVADOS',m.approved]];
stats.forEach(([label,value],i)=>{const x=M+i*CW/3;txt(String(value),x,714,28,bold,accent);txt(label,x,752,7,bold,muted);if(i<2)rect(x+CW/3-19,719,.7,41,edge)});
newPage();
}else if(!compact){const titleLines=wrap(s.title||'Treinamento sem título',CW-16,31,bold),subLines=s.reportSubtitle?wrap(s.reportSubtitle,CW-16,10):[],heroH=112+titleLines.length*41+subLines.length*16;rect(0,0,W,heroH,ink);rect(W-88,0,88,heroH,second);rect(W-18,0,18,heroH,accent);rect(M,34,32,3,second);txt(s.reportMode==='annual'?'BALANÇO ANUAL':'RELATÓRIO DE TREINAMENTO',M,52,8,bold,white);titleLines.forEach((l,i)=>txt(l,M,79+i*41,31,bold,white));let sy=84+titleLines.length*41;subLines.forEach((l,i)=>txt(l,M,sy+i*16,10,normal,white));y=heroH+24;if(logo){drawLogo(M,y,100,35);y+=48}if(s.company)paragraph(s.company,10,accent,bold);if(s.period)paragraph(s.period,9,muted);if(s.scopeLabel)paragraph(s.scopeLabel,8,accent,bold);y+=10}else{if(logo){drawLogo(M,29,90,30);y=75}else y=33;txt(s.reportMode==='annual'?'BALANÇO ANUAL':'RELATÓRIO DE TREINAMENTO',M,y,8,bold,accent);y+=24;paragraph(s.title||'Treinamento sem título',25,ink,bold);if(s.reportSubtitle)paragraph(s.reportSubtitle,10,muted);if(s.company||s.period)paragraph([s.company,s.period,s.scopeLabel].filter(Boolean).join(' · '),8,muted);y+=10}

if(s.contentBuilder?.categories?.length)paragraph(s.contentBuilder.categories.map(k=>ContentBuilder.presets[k].label).join(" · "),9,accent,bold);
const visible=sections(s);
for(let index=0;index<visible.length;index++){const sec=visible[index];activeSection=sec.title;if(!compact&&index>0&&['people','analysis'].includes(sec.id)&&y>H*.48)newPage();if(sec.headers)ensure(sec.months?440:170);heading(sec.title,index+1);
if(sec.headers){paragraph(sec.text);if(sec.months){ensure(150);const max=Math.max(1,...sec.months.map(m=>m.registered)),step=CW/12;sec.months.forEach((m,i)=>{const h=m.registered/max*82;rect(M+i*step+8,y+100-h,step-16,Math.max(1,h),accent);txt(String(m.registered),M+i*step+8,y+85-h,8,bold);txt(m.label,M+i*step+7,y+110,8,normal,muted)});y+=145}table(sec.headers,sec.rows,true)}else if(sec.annualCards){ensure(98);sec.annualCards.forEach(([label,v],i)=>{const w=(CW-24)/4,x=M+i*(w+8);rect(x,y,w,78,pale);rect(x,y,w,3,second);txt(String(v),x+10,y+11,String(v).length>10?10:20,bold,accent);wrap(label,w-20,7,bold).forEach((l,j)=>txt(l,x+10,y+48+j*10,7,bold,muted))});y+=96;paragraph(sec.text)}else if(sec.id==='summary'){const m=metrics(s);metricCards(m);infoPairs([['Multiplicador(a)',s.facilitator],['Público-alvo',s.audience],['Carga horária',s.hours!==''?fmt(s.hours)+' h':''],['Turmas',s.classes],['Plataforma / local',s.platform],['Convocados',s.invited]].filter(p=>p[1]!==''&&p[1]!=null));distribution(m);paragraph('Aprovação: nota mínima '+fmt(s.minGrade)+' / 10 e presença mínima '+fmt(s.minAttendance)+'%. Exige conclusão e os dois dados preenchidos. Pendentes / em avaliação incluem quem está em andamento ou ainda precisa de avaliação.',7,muted);if(numeric(s.invited)&&m.participants>Number(s.invited))paragraph('Confira as participações adicionais: o total de participantes supera o de convocados.',8,red);if(s.link){ensure(45);paragraph('Acesso ao treinamento',8,accent,bold);const linkTop=y;paragraph(s.link,8,accent);if(/^https?:\/\//i.test(s.link)){const a=doc.context.register(doc.context.obj({Type:'Annot',Subtype:'Link',Rect:[M,H-y,CW+M,H-linkTop],Border:[0,0,0],A:{Type:'Action',S:'URI',URI:PDFString.of(s.link)}}));page.node.addAnnot(a)}}
}else if(sec.id==='people'){const rows=s.people.filter(p=>p.name.trim());paragraph(rows.length+' pessoas na relação · critérios definidos para este treinamento',8,muted);if(rows.length)table(s.columns.length?s.columns:['name'],rows);else paragraph('Nenhum participante informado.',9,muted)}
else if(sec.id==='teams'){for(const g of root.TrainingNarrative.groups(s)){const m=g.metrics;callout(g.sector+' · '+g.supervisor,`${m.registered} ${s.reportMode==='annual'?'inscrições':'pessoas cadastradas'} · ${m.participants} participantes · ${m.approved} aprovados · ${m.failed} reprovados.\nMédia: ${fmt(m.average)} (${m.graded} concluintes com nota). Pendentes / em avaliação: ${m.pending}. Ausentes: ${m.absent}.`)}}
else if(sec.id==='recognition'){for(const r of root.TrainingNarrative.recognitions(s)){callout(r.name,[r.identity,r.text].filter(Boolean).join('\n'),second)}}
else if(sec.id==='objective'){callout('PROPÓSITO DO TREINAMENTO',sec.text||'Não informado.',second)}
else if(sec.id==='topics')topicCards(sec.text.split('\n').filter(t=>t.trim()));
else if(sec.id==='schedule')timeline(sec.text.split('\n').filter(t=>t.trim()));
else if(sec.id==='analysis'&&sec.text){for(const block of sec.text.split('\n\n')){const ls=block.split('\n');if(ls.length>1&&ls[0]===ls[0].toLocaleUpperCase('pt-BR'))callout(ls.shift(),ls.join('\n'),ls[0]?.includes('Recomenda')?second:accent);else paragraph(block,10)}}
else paragraph(sec.text||'Não informado.',10,sec.text?ink:muted);y+=compact?7:16}
const pages=doc.getPages();pages.forEach((p,i)=>{page=p;rule(M,H-43,CW);txt(fit(s.author?'Elaborado por '+s.author:s.company||'Treinamento & desenvolvimento',CW-90,7),M,H-31,7,normal,muted);txt(String(i+1).padStart(2,'0')+' / '+String(pages.length).padStart(2,'0'),W-M-40,H-31,7,bold,accent)});return doc.save()}
root.Report={themes,columnNames,sectionNames,numeric,result,metrics,fmt,value,sections,makePDF};
})(typeof window!=='undefined'?window:globalThis);
