(()=>{
const main=document.querySelector('main'),design=document.getElementById('design');
// Reuse original brand controls and listeners, keeping one source of truth.
const identity=document.createElement('section');identity.className='identity-home';identity.setAttribute('aria-label','Escolha sua identidade visual');identity.innerHTML='<div><p class="eyebrow">SEU ESPAÇO DE TRABALHO</p><h2>Qual é a sua identidade?</h2><p>Escolha a marca que acompanha este relatório.</p></div>';
const brands=document.querySelector('.brand-switch');identity.append(brands);main.prepend(identity);
for(const b of brands.querySelectorAll('button')){const image=document.createElement('img');image.src=BrandMedia.logoFor({theme:b.dataset.brand});image.alt='';const title=document.createElement('strong');title.textContent=b.dataset.brand==='b2b'?'Vero B2B':'Vero';const desc=document.createElement('small');desc.textContent=b.dataset.brand==='b2b'?'Time empresarial':'Time Vero';b.replaceChildren(image,title,desc)}
const theme=document.querySelector('[data-field=theme]').closest('label');theme.hidden=true;identity.append(theme);const palette=document.getElementById('palettePreview');palette.hidden=true;identity.append(palette);
// One period disclosure, with both accessible calendar inputs.
const start=document.querySelector('[data-field=startDate]'),end=document.querySelector('[data-field=endDate]');const period=document.createElement('details');period.className='period-picker wide';period.innerHTML='<summary><span>Período do treinamento</span><strong id="periodButtonLabel">Selecionar início e término</strong></summary><div class="fields"></div>';
start.closest('label').before(period);period.querySelector('.fields').append(start.closest('label'),end.closest('label'));
function updatePeriod(){document.getElementById('periodButtonLabel').textContent=TrainingNarrative.period({...state,period:''})||'Selecionar início e término'}
// Duration editors retain canonical decimal hours for old files and imports.
function durationEditor(input){if(!input||input.dataset.durationReady)return;input.dataset.durationReady='1';const label=input.closest('label');let title='Carga horária total';if(input.dataset.person)title='Carga horária da edição';const outer=document.createElement('fieldset');outer.className='duration-editor';const legend=document.createElement('legend');legend.textContent=title;const row=document.createElement('div');row.className='duration-pair';outer.append(legend,row);label.before(outer);input.type='hidden';outer.append(input);label.remove();
const make=(name,max)=>{const l=document.createElement('label');l.textContent=name;const el=document.createElement('input');el.type='number';el.min='0';el.max=String(max);el.step='1';el.className='duration-unit';el.inputMode='numeric';el.setAttribute('aria-label',title+' — '+name);l.append(el);row.append(l);return el};const hours=make('Horas',10000),minutes=make('Minutos',59);const note=document.createElement('small');note.textContent='Ex.: 2 horas e 30 minutos. Deixe vazio para usar a carga importada.';outer.append(note);
input._durationSync=()=>{const total=Report.numeric(input.value)?Math.round(Number(input.value)*60):null;hours.value=total===null?'':Math.floor(total/60);minutes.value=total===null?'':total%60};input._durationSync();
for(const el of [hours,minutes])el.addEventListener('input',()=>{hours.setCustomValidity('');if(!hours.checkValidity()||!minutes.checkValidity())return;const n=Number(hours.value||0)+Number(minutes.value||0)/60;hours.setCustomValidity(n>10000?'A carga total deve ser até 10.000 horas.':'');if(n>10000)return;input.value=hours.value===''&&minutes.value===''?'':String(n);input.dispatchEvent(new Event('input',{bubbles:true}))});
}
function durations(){durationEditor(document.querySelector('[data-field=hours]'));document.querySelectorAll('[data-key=trainingHours]').forEach(durationEditor)}
const oldPeople=renderPeople;renderPeople=function(){oldPeople();durations()};
function meters(){let bar=document.getElementById('participantTotals');if(!bar){bar=document.createElement('div');bar.id='participantTotals';bar.className='participant-totals';bar.setAttribute('aria-live','polite');document.querySelector('#people .section-head').after(bar)}const m=Report.metrics(TrainingNarrative.prepare(state));bar.replaceChildren(...[['Aprovados',m.approved],['Ausentes',m.absent],['Realizaram avaliação',m.evaluated]].map(([name,value])=>{const item=document.createElement('div'),n=document.createElement('strong'),label=document.createElement('span');n.textContent=value;label.textContent=name;item.append(n,label);return item}));bar.title='Totais do recorte do relatório. Avaliação: nota informada, inclusive zero. A busca por nome não muda esses totais.'}
const oldPreview=preview;preview=function(){oldPreview();updatePeriod();meters()};const oldSync=sync;sync=function(){oldSync();document.querySelectorAll('[data-duration-ready]').forEach(el=>el._durationSync?.());updatePeriod()};
// Reveal invalid fields even inside a collapsed section before native validation.
function revealInvalid(){const el=document.querySelector('#form :invalid');if(!el)return true;const panel=el.closest('.panel');if(panel)setTab(tabs.indexOf(panel.id));for(let p=el.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;el.reportValidity();el.focus();return false}
const previousValidate=validateExport;validateExport=function(){return revealInvalid()&&previousValidate()};const save=document.getElementById('save'),saveHandler=save.onclick;save.onclick=()=>{if(!revealInvalid())return;saveHandler()};
// Art direction: visible model collection, then focused optional sections.
const style=document.querySelector('[data-field=reportStyle]');style.closest('label').hidden=true;const gallery=document.createElement('div');gallery.className='model-gallery';gallery.setAttribute('role','group');gallery.setAttribute('aria-label','Modelo do relatório');
const models=[['premium','Editorial da marca','Capa, retrato e resultados'],['editorial','Editorial','Conteúdo em blocos visuais'],['executive','Dossiê executivo','Indicadores em destaque'],['magazine','Revista Em Foco','Composição de revista'],['compact','Executivo compacto','Leitura objetiva']];
for(const [value,title,desc] of models){const b=document.createElement('button');b.type='button';b.dataset.modelChoice=value;const thumbnail=document.createElement('span');thumbnail.className='model-thumbnail thumb-'+value;thumbnail.setAttribute('aria-hidden','true');thumbnail.innerHTML='<i></i><b></b><em></em><span></span>';const name=document.createElement('strong');name.textContent=title;const hint=document.createElement('small');hint.textContent=desc;b.append(thumbnail,name,hint);b.onclick=()=>{style.value=value;style.dispatchEvent(new Event('input',{bubbles:true}));updateModels()};gallery.append(b)}
style.closest('label').before(gallery);function updateModels(){gallery.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.modelChoice===state.reportStyle)))}
new MutationObserver(updateModels).observe(document.getElementById('preview'),{attributes:true,attributeFilter:['data-model']});updateModels();
const head=design.querySelector('.section-head');head.querySelector('h2').textContent='Direção de arte do relatório';head.querySelector('p').textContent='Escolha uma composição. Refine a capa, a narrativa e os detalhes.';
function group(title,hint,nodes){const card=document.createElement('details');card.className='ui-disclosure design-group';const summary=document.createElement('summary');const strong=document.createElement('span');strong.textContent=title;const small=document.createElement('small');small.textContent=hint;summary.append(strong,small);const body=document.createElement('div');body.className='design-group-body';card.append(summary,body);for(const n of nodes.filter(Boolean))body.append(n);design.insertBefore(card,document.getElementById('newReport'));return card}
const subtitle=document.querySelector('[data-field=reportSubtitle]').closest('label');group('Capa e imagens','Subtítulo, marca e personagem',[subtitle,...design.querySelectorAll('.logo-upload')]);
const order=document.getElementById('sectionOrder'),columns=document.getElementById('columnOptions');const orderHint=order.previousElementSibling,orderTitle=orderHint.previousElementSibling,columnsTitle=columns.previousElementSibling;group('Estrutura da apresentação','Seções, ordem e colunas',[orderTitle,orderHint,order,columnsTitle,columns]);group('Continuidade do trabalho','Rascunho e edição',[design.querySelector('.rule-box')]);
for(const hint of [...design.children].filter(n=>n.classList.contains('hint')))hint.remove();
// Separate outputs by purpose. Existing buttons/handlers stay intact.
const grid=document.querySelector('.download-grid');const groups=[['Apresentar e compartilhar',['pdf','docxvisual','html','png','eml']],['Editar e trabalhar os dados',['docx','xlsx','csv','tsv']],['Texto e ferramentas de IA',['md','txt','json','jsonl']],['Continuar no sistema',['backup']]];
for(const [name,types] of groups){const section=document.createElement('section');section.className='download-family';const h=document.createElement('h3');h.textContent=name;const g=document.createElement('div');g.className='download-grid';for(const type of types){const b=grid.querySelector('[data-download='+type+']');if(b)g.append(b)}section.append(h,g);grid.before(section)}grid.remove();
durations();updatePeriod();meters();
})();

// Styled workbook, keeping exactly the ordered content of the visible report.
globalThis.StudioWorkbook=async function(){
const snap=ReportSnapshot.snapshot(),book=new ExcelJS.Workbook();book.creator='Edson Luciano';book.title=state.title||'Relatório de treinamento';const color=state.theme==='b2b'?'253072':'D61960',deep=state.theme==='b2b'?'091441':'830F2E';
const sheet=book.addWorksheet('Relatório',{views:[{showGridLines:false}],pageSetup:{paperSize:9,orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0}});const width=Math.max(4,...snap.blocks.filter(b=>b.type==='table').map(b=>Math.max(...b.rows.map(r=>r.length))));sheet.columns=Array.from({length:width},()=>({width:22}));sheet.properties.defaultRowHeight=24;
function row(ws,values,kind){const r=ws.addRow(values);r.eachCell({includeEmpty:true},c=>{c.font={name:'Arial',size:11,color:{argb:'FF5F5F5F'}};c.alignment={vertical:'top',wrapText:true};c.border={bottom:{style:'hair',color:{argb:'FFD3D2CF'}}};if(kind==='heading'||kind==='header'){c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF'+color}};c.font={name:'Arial',size:kind==='heading'?14:11,bold:true,color:{argb:'FFFFFFFF'}}}});r.height=Math.min(409,Math.max(kind==='heading'?34:26,...values.map((v,i)=>Math.ceil(String(v??'').length/(values.length===1?width*16:20))*16+12)));if(values.length===1){ws.mergeCells(r.number,1,r.number,width);r.getCell(1).alignment={wrapText:true,vertical:'top'}}return r}
let tableIndex=0;
for(const b of snap.blocks){if(b.type==='image')continue;if(b.type==='table'){b.rows.forEach((r,i)=>row(sheet,r,i<b.headerRows?'header':'body'));sheet.addRow([]);const sub=book.addWorksheet('Tabela '+(++tableIndex),{views:[{state:'frozen',ySplit:b.headerRows||0,showGridLines:false}]});sub.columns=Array.from({length:Math.max(...b.rows.map(r=>r.length))},()=>({width:26}));b.rows.forEach((r,i)=>{const n=sub.addRow(r);n.height=38;n.eachCell(c=>{c.alignment={wrapText:true,vertical:'middle'};c.font={name:'Arial',size:11,color:{argb:i<b.headerRows?'FFFFFFFF':'FF5F5F5F'},bold:i<b.headerRows};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:i<b.headerRows?'FF'+color:(i%2?'FFEDF0EE':'FFFFFFFF')}};});});if(b.headerRows===1&&b.rows.length>1)sub.autoFilter={from:{row:1,column:1},to:{row:b.rows.length,column:sub.columnCount}}}
else if(b.type==='list'){b.items.forEach((v,i)=>row(sheet,[(b.ordered?(i+1)+'. ':'• ')+v],'body'))}
else row(sheet,[b.text],b.type==='heading'?'heading':'body')}
return await book.xlsx.writeBuffer();
};
