(function(root){
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function duration(value){const s=String(value||'').trim().toLowerCase().replace(',','.');if(/^\d+:\d{2}(:\d{2})?$/.test(s)){const a=s.split(':').map(Number);if(a.slice(1).some(n=>n>59))return null;return a.length===3?a[0]*3600+a[1]*60+a[2]:a[0]*60+a[1]}let seconds=0,found=false;const rest=s.replace(/(\d+(?:\.\d+)?)\s*(hours?|hrs?|horas?|h|minutos?|minutes?|mins?|m|segundos?|seconds?|secs?|s)\b/g,(_,n,u)=>{found=true;seconds+=Number(n)*(u[0]==='h'?3600:u[0]==='m'?60:1);return ''});return found&&!rest.trim()?seconds:null}
function decode(buffer){const b=new Uint8Array(buffer);let s=new TextDecoder(b[0]===255&&b[1]===254?'utf-16le':b[0]===254&&b[1]===255?'utf-16be':b[1]===0&&b[3]===0?'utf-16le':'utf-8').decode(buffer);if(s.includes('\uFFFD'))s=new TextDecoder('windows-1252').decode(buffer);return s.replace(/^\uFEFF/,'')}
function parse(text){const rows=ParticipantImport.textRows(text);let header=-1,map;for(let i=0;i<rows.length;i++){const n=rows[i].map(norm),name=n.findIndex(v=>['nome','name','full name','nome completo'].includes(v)),time=n.findIndex(v=>['duration','duracao','duracao da reuniao','in meeting duration','duracao na reuniao','tempo em reuniao','tempo na reuniao'].includes(v));if(name>=0&&time>=0){header=i;map={name,time,email:n.findIndex(v=>['email','e mail','endereco de email','email address'].includes(v))};break}}if(header<0)throw Error('Não encontrei a tabela de participantes com Nome e Duração na reunião. Exporte o relatório de presença do Teams em CSV.');const out=[];for(const row of rows.slice(header+1)){if(/^3[.\s]/.test(String(row[0]))||/^(atividades (da|de) reuniao|in meeting activities)/.test(norm(row[0])))break;if(row.length<=map.time||!row[map.name])continue;const seconds=duration(row[map.time]);if(seconds===null)throw Error('Duração não reconhecida para '+row[map.name]+': '+row[map.time]);out.push({name:row[map.name],email:map.email>=0?row[map.email]||'':'',seconds})}if(!out.length)throw Error('A tabela de presença está vazia.');if(out.length>5000)throw Error('Limite de 5.000 participantes.');return out}
function plan(people,rows,session){const seen=new Set();return rows.map(row=>{const email=row.email.trim().toLowerCase(),identity=email||norm(row.name),duplicate=seen.has(identity);seen.add(identity);const scope=people.filter(p=>norm(p.training)===norm(session.training)&&p.trainingStart===session.start&&p.trainingEnd===session.end);const exact=email?scope.filter(p=>p.email.trim().toLowerCase()===email):[];const byName=scope.filter(p=>norm(p.name)===norm(row.name)&&(!email||!p.email.trim()));const matches=exact.length?exact:byName;let error=duplicate?'Identidade repetida no CSV. Revise o arquivo.':matches.length>1?'Mais de um cadastro corresponde a esta pessoa. Revise os cadastros.':'';if(!error&&!matches.length&&scope.some(p=>norm(p.name)===norm(row.name)))error='Nome encontrado com outro e-mail. Revise antes de importar.';const attendance=Math.min(100,Math.round(row.seconds/(session.hours*3600)*10000)/100);return{...row,target:matches.length===1?matches[0].id:null,attendance,error,selected:!error}})}
root.TeamsAttendance={parse,decode,duration,plan};
if(typeof document==='undefined')return;
let rows=[],pending=[],session=null,revision=0;const d=$('#teamsDialog');
function reset(){revision++;pending=[];$('#applyTeams').disabled=true;$('#teamsTable').innerHTML='';$('#teamsSummary').textContent='Confira os dados para preparar a atualização.'}
$('#openTeams').onclick=()=>{reset();rows=[];$('#teamsFile').value='';$('#teamsTraining').value=state.reportTraining||state.title;$('#teamsStart').value=state.filterStart||state.startDate;$('#teamsEnd').value=state.filterEnd||state.endDate;$('#teamsHours').value=state.hours;d.showModal()};$('#closeTeams').onclick=()=>d.close();
for(const id of ['teamsTraining','teamsStart','teamsEnd','teamsHours','teamsFile']){$('#'+id).onchange=reset;$('#'+id).oninput=reset;}
$('#reviewTeams').onclick=async()=>{reset();const rev=revision;try{session={training:$('#teamsTraining').value.trim(),start:$('#teamsStart').value,end:$('#teamsEnd').value,hours:Number($('#teamsHours').value)};if(!session.training||!session.start||!session.end||session.end<session.start||!Number.isFinite(session.hours)||session.hours<=0||session.hours>10000)throw Error('Informe treinamento, datas válidas e duração maior que zero.');const f=$('#teamsFile').files[0];if(!f)throw Error('Selecione o CSV exportado pelo Teams.');if(f.size>20*1024*1024)throw Error('O arquivo deve ter até 20 MB.');const buffer=await f.arrayBuffer();if(rev!==revision)return;rows=parse(decode(buffer));pending=plan(state.people,rows,session);$('#teamsTable').innerHTML='<thead><tr><th>Incluir</th><th>Nome</th><th>E-mail</th><th>Presença</th><th>Atualização</th></tr></thead><tbody>'+pending.map((p,i)=>'<tr><td><input type="checkbox" data-teams-row="'+i+'" '+(p.error?'disabled':'checked')+' aria-label="Incluir '+esc(p.name)+'"></td><td>'+esc(p.name)+'</td><td>'+esc(p.email)+'</td><td>'+p.attendance+'%</td><td>'+esc(p.error||(p.target?'Atualizar somente presença':'Novo participante · Em andamento'))+'</td></tr>').join('')+'</tbody>';$$('[data-teams-row]').forEach(el=>el.onchange=()=>{pending[Number(el.dataset.teamsRow)].selected=el.checked;$('#applyTeams').disabled=!pending.some(p=>p.selected)});$('#teamsSummary').textContent=pending.filter(p=>p.target&&!p.error).length+' atualizações · '+pending.filter(p=>!p.target&&!p.error).length+' novos · '+pending.filter(p=>p.error).length+' bloqueados para revisão.';$('#applyTeams').disabled=!pending.some(p=>p.selected)}catch(e){$('#teamsSummary').textContent=e.message}};
$('#applyTeams').onclick=()=>{const selected=pending.filter(p=>p.selected&&!p.error);if(!selected.length)return;const fresh=plan(state.people,rows,session);if(selected.some(p=>{const q=fresh.find(q=>q.name===p.name&&q.email===p.email);return !q||q.error||q.target!==p.target})){reset();toast('Os cadastros mudaram. Confira a atualização novamente.');return}if(state.people.length+selected.filter(p=>!p.target).length>5000){toast('Limite de 5.000 participantes.');return}for(const p of selected){if(p.target){state.people.find(q=>q.id===p.target).attendance=p.attendance}else state.people.push({...person(),name:p.name,email:p.email,training:session.training,trainingStart:session.start,trainingEnd:session.end,trainingHours:session.hours,attendance:p.attendance,status:'Em andamento'})}state.columns=[...new Set([...state.columns,'training','trainingStart','trainingEnd','attendance'])];sync();changed();d.close();toast(selected.length+' presenças aplicadas. Notas e avaliações existentes foram preservadas.');pending=[]};
})(globalThis);
