(function(root){
const groups={
 goals:{title:'1. O que o treinamento busca desenvolver?',items:{communication:['Comunicação clara','desenvolver uma comunicação clara, objetiva e acolhedora'],process:['Domínio dos processos','ampliar o domínio dos processos e ferramentas da operação'],retention:['Argumentação em retenção','desenvolver argumentação orientada às necessidades do cliente'],technical:['Diagnóstico técnico','aprimorar o diagnóstico e a resolução de demandas técnicas'],quality:['Qualidade e padronização','alinhar a execução às boas práticas de qualidade'],safety:['Segurança operacional','reforçar os cuidados de segurança nas atividades operacionais']}},
 topics:{title:'2. Quais temas foram abordados?',items:{rapport:['Rapport e escuta ativa','Rapport, escuta ativa e identificação das necessidades do cliente'],clarity:['Comunicação e acolhimento','Comunicação clara, acolhimento e confirmação de entendimento'],crm:['CRM e registros','Uso de CRM e registro das informações do atendimento'],billing:['Faturas e cobrança','Faturas, meios de pagamento e procedimentos de cobrança'],support:['Suporte técnico','Diagnóstico e procedimentos de suporte técnico'],objections:['Retenção e objeções','Argumentação em retenção e tratamento de objeções'],plans:['Planos e negociação','Planos, ofertas e possibilidades de negociação'],flow:['Fluxos e processos','Fluxos operacionais e direcionamento das demandas'],products:['Produtos e serviços','Características, benefícios e aplicação dos produtos e serviços'],wifi:['Wi-Fi e equipamentos','Redes Wi-Fi e configuração de equipamentos'],fiber:['Fibra e conectores','Fibra óptica, redes FTTx e boas práticas com conectores'],safety:['Segurança e ferramentas','Segurança no trabalho e uso adequado das ferramentas'],apps:['Aplicativos operacionais','Utilização dos aplicativos e sistemas operacionais'],closing:['Encerramento e entrega','Encerramento do atendimento e confirmação da solução']}},
 methods:{title:'3. Como o conteúdo foi trabalhado?',items:{presentation:['Exposição dialogada','exposição dialogada dos conceitos'],demo:['Demonstração de sistemas','demonstração orientada dos sistemas e procedimentos'],cases:['Estudos de caso','análise de situações práticas e estudos de caso'],simulation:['Simulações de atendimento','simulações de atendimento'],practice:['Prática acompanhada','prática acompanhada com orientação'],questions:['Esclarecimento de dúvidas','esclarecimento de dúvidas'],test:['Avaliação de aprendizagem','avaliação de aprendizagem']}},
 observations:{title:'4. O que você observou na turma?',hint:'Marque apenas o que foi efetivamente observado. Nenhuma opção vem marcada.',items:{engagement:['Participação ativa','participação ativa nas atividades propostas'],exchange:['Troca de experiências','troca de experiências entre participantes'],questions:['Dúvidas sobre processos','dúvidas relacionadas à aplicação dos processos'],systems:['Dificuldade com sistemas','dificuldades na utilização dos sistemas'],argument:['Dificuldade na argumentação','necessidade de aprofundamento da argumentação'],practice:['Necessidade de mais prática','necessidade de ampliar a prática orientada']}},
 actions:{title:'5. Quais próximos passos serão recomendados?',items:{review:['Revisão dos conteúdos','retomar os conteúdos que demandam reforço'],coaching:['Acompanhamento na operação','acompanhar a aplicação dos conteúdos na operação'],materials:['Material de apoio','disponibilizar material de apoio para consulta'],practice:['Prática complementar','realizar atividades práticas complementares'],retest:['Nova avaliação','programar uma nova avaliação após o reforço'],leaders:['Alinhamento com gestores','alinhar com os gestores as necessidades de acompanhamento']}},
 stages:{title:'6. Quais etapas compõem o cronograma?',hint:'As etapas seguem a ordem abaixo; datas e duração podem ser ajustadas no texto.',items:{welcome:['Abertura e alinhamento','Abertura e alinhamento dos objetivos'],concepts:['Apresentação dos conteúdos','Apresentação dos conceitos e processos'],demo:['Demonstração orientada','Demonstração das ferramentas e procedimentos'],practice:['Atividades práticas','Aplicação prática e exercícios orientados'],questions:['Revisão e dúvidas','Revisão dos conteúdos e esclarecimento de dúvidas'],test:['Avaliação','Avaliação de aprendizagem'],followup:['Acompanhamento','Acompanhamento da aplicação na operação']}}
};
const presets={retention:{label:'Retenção',goals:['communication','retention'],topics:['rapport','objections','plans','flow']},multi:{label:'Multiskill',goals:['communication','process','technical'],topics:['clarity','crm','billing','support','flow']},technical:{label:'Técnico / campo',goals:['technical','quality','safety'],topics:['fiber','wifi','safety','apps','closing']},products:{label:'Produtos / comercial',goals:['communication','process'],topics:['products','plans','crm']},rapport:{label:'Rapport',goals:['communication','quality'],topics:['rapport','clarity','objections','closing']}};
const fields=['objective','topics','schedule','analysis'];
function blank(){return{categories:[],...Object.fromEntries(Object.keys(groups).map(k=>[k,[]])),extraTopics:'',note:'',includeMetrics:false,auto:Object.fromEntries(fields.map(k=>[k,true]))}}
function validate(v){const out=blank();if(!v||typeof v!=='object'||Array.isArray(v))throw Error('Seleções de conteúdo inválidas.');if(v.categories!==undefined){if(!Array.isArray(v.categories)||v.categories.some(k=>!Object.hasOwn(presets,k)))throw Error('Categoria inválida.');out.categories=[...new Set(v.categories)]}for(const k of Object.keys(groups)){if(!Array.isArray(v[k])||v[k].some(x=>typeof x!=='string'||!Object.hasOwn(groups[k].items,x)))throw Error('Opção de conteúdo inválida.');out[k]=[...new Set(v[k])]}for(const k of ['extraTopics','note']){if(typeof v[k]!=='string')throw Error('Complemento de conteúdo inválido.');out[k]=v[k]}if(typeof v.includeMetrics!=='boolean')throw Error('Opção de indicadores inválida.');out.includeMetrics=v.includeMetrics;for(const k of fields){if(typeof v.auto?.[k]!=='boolean')throw Error('Modo de preenchimento inválido.');out.auto[k]=v.auto[k]}return out}
const list=arr=>arr.length<2?(arr[0]||''):arr.slice(0,-1).join(', ')+' e '+arr.at(-1);
function compose(s){const b=s.contentBuilder||blank(),selected=k=>Object.keys(groups[k].items).filter(id=>b[k].includes(id)).map(id=>groups[k].items[id][1]);const goals=selected('goals'),topics=[...selected('topics'),...b.extraTopics.split('\n').map(t=>t.trim()).filter(Boolean)],methods=selected('methods'),observations=selected('observations'),actions=selected('actions'),stages=selected('stages');const audience=s.audience?.trim();const named=s.title?.trim()?`O treinamento “${s.title.trim()}”`:'O treinamento';const pick=(key,options)=>root.TrainingNarrative?root.TrainingNarrative.pick(s,key,options):options[0];const objective=goals.length?pick('objective',[`${named}${audience?', voltado a '+audience+',':''} tem como objetivo ${list(goals)}.`,`${named} busca ${list(goals)}${audience?', com foco no público '+audience:''}.`,`${named} foi planejado para ${list(goals)}${audience?', considerando as demandas de '+audience:''}.`]):'';const parts=[];if(topics.length||methods.length||observations.length||actions.length||b.includeMetrics){const context=[s.period?'Período: '+s.period:'',audience?'Público: '+audience:'',s.scopeLabel||''].filter(Boolean);if(s.title||context.length)parts.push('CONTEXTO DO TREINAMENTO\n'+[s.title, ...context].filter(Boolean).join(' · ')+'.')}
if(topics.length)parts.push('DESENVOLVIMENTO\n'+pick('topics',[`Neste treinamento, trabalhei ${list(topics.map(t=>t.charAt(0).toLocaleLowerCase('pt-BR')+t.slice(1)))}.`,`Trabalhei ${list(topics.map(t=>t.charAt(0).toLocaleLowerCase('pt-BR')+t.slice(1)))}.`,`Abordei ${list(topics.map(t=>t.charAt(0).toLocaleLowerCase('pt-BR')+t.slice(1)))}.`]));
if(methods.length)parts.push('METODOLOGIA\n'+pick('methods',[`Combinei ${list(methods)}.`,`Para trabalhar os conteúdos, utilizei ${list(methods)}.`,`Trabalhei com ${list(methods)}.`]));
if(observations.length)parts.push('OBSERVAÇÕES DA TURMA\n'+pick('observations',[`Durante as atividades, observei ${list(observations)}.`,`Na interação com a turma, observei ${list(observations)}.`,`Ao acompanhar a turma, registrei ${list(observations)}.`]));
if(b.includeMetrics){const m=root.Report.metrics(s),q=root.TrainingNarrative.count;if(m.registered){let p=`A base preenchida reúne ${q(m.registered,'pessoa')}, com ${q(m.participants,'participante')}, ${q(m.absent,'ausente')}, ${q(m.approved,'aprovado')} e ${q(m.failed,'reprovado')}.`;p+=m.average===null?' Não há notas de concluintes informadas para calcular a média.':` A média é ${root.Report.fmt(m.average)}, considerando ${q(m.graded,'concluinte')} com nota informada.`;p+=` ${m.pending===1?'Há 1 pessoa pendente, em andamento ou a avaliar.':`Há ${m.pending} pessoas pendentes, em andamento ou a avaliar.`}`;parts.push('INDICADORES REGISTRADOS\n'+p)}else parts.push('INDICADORES REGISTRADOS\nNão há participantes cadastrados para análise dos resultados.')}

if(actions.length)parts.push('PRÓXIMOS PASSOS RECOMENDADOS\n'+pick('actions',[`Como continuidade, recomenda-se ${list(actions)}.`,`Os próximos passos sugeridos são ${list(actions)}.`,`Para dar seguimento ao desenvolvimento da turma, a recomendação é ${list(actions)}.`]));
if(b.note.trim())parts.push('REGISTRO COMPLEMENTAR\n'+b.note.trim());
return{objective,topics:topics.join('\n'),schedule:stages.map((t,i)=>`Etapa ${i+1}: ${t}`).join('\n'),analysis:parts.join('\n\n')}}
root.ContentBuilder={groups,presets,fields,blank,validate,compose};
})(typeof window!=='undefined'?window:globalThis);
